# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

  desc "Push a new release build to the App Store"
  lane :beta do
    match(
      type: "appstore",
      readonly: true, 
      app_identifier: [ENV['APP_IDENTIFIER'], ENV['APP_IDENTIFIER_EXTENSION']]
    )
    clear_derived_data
    increment_build_number(
	timeout: 600,
    	build_number: latest_testflight_build_number + 1
    )
    gym(
     clean: true,
     scheme: "FocusTimer",
     timeout: 600,
     export_method: "app-store",
     export_options: {
       provisioningProfiles: {
	 ENV['APP_IDENTIFIER'] => "match AppStore #{ENV['APP_IDENTIFIER']}",
	 ENV['APP_IDENTIFIER_EXTENSION'] => "match AppStore #{ENV['APP_IDENTIFIER_EXTENSION']}"
       }
     }
    )
    upload_to_testflight
    slack(
     message: "Testflight 배포 성공",
     slack_url: ENV['SLACK_URL']
    )
end

platform :ios do

  error do |lane, exception, options|
    slack(
      message: "에러 발생: #{exception}",
      success: false,
      slack_url: ENV['SLACK_URL']
  )
    end 
  end
